Linear Search/linearsearch.cpp
=> added linear search in cpp

BinarySearch/binary_search.py
I have added a binary search algo in python please merge it.
=> Added Binary search 

BinarySearch/iterative_binary_search.py
=> Iterative Binary search added

BinarySearch/binary_search.cpp
=> binary search in cpp added

Selection sort/selection_sort.py
=> Selection sort

Selection sort/selection_sort.cpp
=> selection sort in cpp added

important algo related problems/infosys_palindrome.py
=> Important placement problems

KMP Algorithm/kmpAlgorithm.cpp
=> KMP Alogorithm for Pattern matching added

important algo related problems/bfs_of_a_graph.py
=> Graph algos added

important algo related problems/missing_and_repeating.py, important algo related problems/sort_an_array_0_1_2.py
=> updates in arrays

QuickSort/quicksort.cpp
=> quicksort in cpp

A star algorithm/A_star.py
- A* (pronounced "A-star") is a graph traversal and path search algorithm, which is often used in many fields of computer science due to its completeness, optimality, and optimal efficiency.
-  A * aims to find a path to the given goal node having the smallest cost (least distance travelled, shortest time, etc.).
- At each iteration of its main loop, A* needs to determine which of its paths to extend. It does so based on the cost of the path and an estimate of the cost required to extend the path all the way to the goal. Specifically, A* selects the path that minimizes
f(n)=g(n)+h(n) where n is the next node on the path, g(n) is the cost of the path from the start node to n, and h(n) is a heuristic function that estimates the cost of the cheapest path from n to the goal.
=> Added A-star algorithm for finding shortest path in a graph

QuickSort/quicksort.py
=> Quiksort in python

Bellman Ford algorithm/bellmanFord.py
- The Bellman–Ford algorithm is an algorithm that computes shortest paths from a single source vertex to all of the other vertices in a weighted digraph.
- It is slower than Dijkstra's algorithm for the same problem, but more versatile, as it is capable of handling graphs in which some of the edge weights are negative numbers.
- Like Dijkstra's algorithm, Bellman–Ford proceeds by relaxation, in which approximations to the correct distance are replaced by better ones until they eventually reach the solution.
=> Added Bellman ford algorithm to compute shortest paths from a single source vertex to all of the other vertices in a weighted digraph.

important algo related problems/armstrong.py
- This python program determines if a given number is an armstrong number or not.
- In number theory, a armstrong number in a given number base b is a number that is the sum of its own digits each raised to the power of the number of digits.
- *Time Complexity: O(n)*
- *Space Complexity: O(1)*
=> An Approach to determine whether a number is armstrong or not

Dijkstra's Algorithm/dijkstra.py
- Dijkstra's algorithm is an algorithm for finding the shortest paths between nodes in a graph.
- This algorithm makes no attempt of direct "exploration" towards the destination as one might expect. Rather, the sole consideration in determining the next "current" intersection is its distance from the starting point.
- This algorithm therefore expands outward from the starting point, interactively considering every node that is closer in terms of shortest path distance until it reaches the destination.
- *Time Compleity: O( | V | ^ 2 )*
=> Dijkstra's algorithm to find shortest path from source to destination

important algo related problems/jumpGame.py
The Leet code problem [Jump Game](https://leetcode.com/problems/jump-game/)  comes under Dynamic programming and can be solved using a single loop with two pointers.
*Time complexity: O(n)*
*Space complexity: O(n)*
=> Added a solution for leet code's Jump Game problem using python

Heapsort/Heapsort.cpp, Heapsort/heapsort.py
Updated the code of heapsort in cpp
=> heapsort added

Heapsort/heapsort.py
Updated the code of heapsort in py
=> Updated heapsort.py

Heapsort/heapsort.java
Updated the code of heapsort in java
=> added heapsort in java language

Heapsort/heapsort.js
Updated the code of heapsort in javascript
=> created heap sort using javascript

Luhn algorithm/Luhn.py
Hacktober tag would be welcome. Algorithm used for verification of ID and credit card numbers.
=> Added Luhns algorithm
